# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

google-ID: 'UA-112060364-2'

menu:
- {name: 'Intro', folder: 'pages', file: 'intro.html'}
- {name: 'People', folder: 'pages', file: 'people.html'}
- {name: 'Schools', folder: 'pages', file: 'sample-posts.html'}
- {name: 'Activities', folder: 'pages', file: 'documentation.html'}
- {name: 'Gallery', folder: 'pages', file: 'about.html'}
- {name: 'Contact', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/paululele'}
- {icon: 'facebook', link: 'https://www.facebook.com/profile.php?id=100002269882529'}
- {icon: 'instagram', link: 'https://www.instagram.com/jacqueline.jw/'}
- {icon: 'envelope', link: 'jingwen.wang96@gmail.com'}
- {icon: 'rss-square', link: 'feed.xml'}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
